### PR TITLE
Update examples to use mergedConfiguration so image labels work

### PR DESCRIPTION
**Pull request by Chuxel**
Takes advantage of the new mergedConfiguration section in config output to simplify the script and pick up image label info.

Also made a minor tweak to properly return the right exit code from the CI example.

### CODE REVIEW

**Comment by Chuxel** [comment]
The CI failure reported here does not seem to be related to this change.

**Review by bamurtaugh — COMMENTED** [review]
Thanks for making these changes!

It's been a bit since I've run the examples, so perhaps you can help me refresh my memory on what/how I should be checking. Here's what I tried:

- Open devcontainers/cli on the example-tweaks branch locally
- `yarn` and `yarn compile` to ensure CLI is working properly
- Type `example-usage/tool-vscode-server/start.sh` in integrated terminal
- When I visit http://localhost:8000/, it can't be reached

**Comment by Chuxel** [comment]
> * example-usage/tool-vscode-server/start.sh

I use the deployed version of the CLI for testing.

```
npm install -g @devcontainers/cli
```

Possible there is a bug with local install - or it's finding an out-of-date version of the CLI.  Does that work?  If not, are there any errors?

**Review by bamurtaugh — APPROVED** [review]
Thanks for the guidance, got it working now and LGTM!

**Pull request merged**
