### PR TITLE
Use make-fetch-happen instead of follow-redirects

### LINKED ISSUE #185: Missing HTTP proxy support
Hello,

The CLI is not able to do HTTP(S) requests through a proxy. This seems to be inherent to Node.js not supporting proxies (see https://github.com/nodejs/node/issues/8381).
However, solutions seem to exist, e.g. https://www.npmjs.com/package/global-agent.

I would be happy to submit a PR if you want me to.

### PR DESCRIPTION
**Pull request by cailloumajor**
## Description

Those changes makes use of [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen) package in place of [follow-redirects](https://www.npmjs.com/package/follow-redirects) for fetch operations, with the goal to handle using the CLI behind an HTTP proxy.

Fixes #185.

## What tests have been done?

To confirm the changes work as expected and that no regression is introduced, I ran the test suite (`yarn package` followed with `yarn test`) in the following scenarios:

| Before/after changes | Internet connection | Tests result       | Observations   |
| -------------------  | ------------------- | :----------------: | -------------- |
| before               | Direct              | :heavy_check_mark: |                |
| before               | Behind a proxy*     | :x:                | Network errors |
| after                | Direct              | :heavy_check_mark: |                |
| after                | Behind a proxy*     | :heavy_check_mark: |                |

\*without authentication

### CODE REVIEW

**Comment by cailloumajor** [comment]
@microsoft-github-policy-service agree

**Comment by cailloumajor** [comment]
Is there anything blocking that I could help with?

**Comment by chrmarti** [comment]
@cailloumajor Thanks for you PR! After careful consideration I realized that `make-fetch-happen` pulls in many additional dependencies. I have now fixed this using `proxy-agent` in https://github.com/devcontainers/cli/pull/218 which comes with fewer dependencies. Hope that makes sense, thanks again for your contribution!

**Comment by cailloumajor** [comment]
> @cailloumajor Thanks for you PR! After careful consideration I realized that `make-fetch-happen` pulls in many additional dependencies. I have now fixed this using `proxy-agent` in #218 which comes with fewer dependencies. Hope that makes sense, thanks again for your contribution!

@chrmarti it totally makes sense. I quickly tested behind a proxy with `./devcontainer.js features info ghcr.io/devcontainers/features/common-utils`, with success.
Thank you for the fix!

P.S.: Do you have an idea (or a mean to know) when this will land in VS Code?

**Comment by chrmarti** [comment]
@cailloumajor It's in Dev Containers 0.259.0-pre-release.

**Comment by chrmarti** [comment]
(Now also available in Dev Containers 0.255.3.)

**Comment by cailloumajor** [comment]
> (Now also available in Dev Containers 0.255.3.)

:tada: thanks!

**Pull request closed without merging**
